import json
import os
from typing import Any, Dict, Optional
from harness.engine.state import TaskState
from harness.telemetry.metrics import TaskMetrics


def generate_markdown_report(
    state: TaskState,
    git_diff: str = "",
    verification_summary: str = "",
) -> str:
    """Generates an executive evaluation report in GitHub Markdown format."""
    metrics = TaskMetrics.from_task_state(state)

    tool_usage_str = (
        ", ".join([f"`{k}`: {v}" for k, v in metrics.tool_usage_counts.items()])
        if metrics.tool_usage_counts
        else "None"
    )

    files_list = (
        "\n".join([f"- `{f}`" for f in state.files_modified])
        if state.files_modified
        else "_No files modified_"
    )

    diff_section = (
        f"```diff\n{git_diff.strip()}\n```"
        if git_diff.strip()
        else "_No uncommitted git diff detected._"
    )

    verif_text = verification_summary or state.verification_status or "Unverified"
    status_str = state.status.value if hasattr(state.status, "value") else str(state.status)

    report = f"""# Autonomous AI Coding Execution Report

## Task Overview
- **Task ID:** `{state.task_id}`
- **Repository:** `{state.repo_path}`
- **Model Used:** `{state.model}`
- **Status:** **{status_str}**
- **Verification Status:** `{verif_text}`
- **Failure Category:** `{metrics.failure_category or 'None'}`
- **Created At:** {state.created_at}
- **Completed At:** {state.completed_at or 'In Progress / Interrupted'}
- **Task Duration:** `{metrics.task_duration_seconds}s`

---

## Issue / Task Description
> {state.issue_description}

---

## Executive Summary & Final Result
{state.final_summary or state.final_result or (state.error_message if state.error_message else '_No final summary provided._')}

---

## Metrics & Resource Usage
- **Total Autonomous Steps:** `{state.current_step} / {state.max_steps}`
- **Total Tool Invocations:** `{metrics.total_tool_calls} / {state.max_tool_calls}`
- **Total Tokens Consumed:** `{state.total_tokens_consumed}`
- **Errors Encountered / Retried:** `{metrics.errors_encountered} (Retries: {metrics.retry_count})`
- **Tests Executed / Passed / Failed:** `{metrics.test_runs_count} runs ({metrics.test_passes_count} passed, {metrics.test_failures_count} failed)`
- **Tool Usage Breakdown:** {tool_usage_str}

---

## Modified Files
{files_list}

---

## Git Diff (Changes Applied)
{diff_section}

---

## Known Limitations & Verification Notes
- Sandbox limits command execution to workspace root and allowed development executables.
- Secret environment variables (API keys, credentials) were sanitized from process environments and telemetry logs.

---

## Execution Step Trajectory
| Step | Stage | Action / Tool | Result Status | Tokens |
| :--- | :--- | :--- | :--- | :--- |
"""
    for s in state.steps:
        tool_desc = f"`{s.tool_name}`" if s.tool_name else "_Reasoning only_"
        status_desc = "❌ Error" if s.is_error else "✅ Success"
        stage_str = s.stage.value if hasattr(s.stage, "value") else str(s.stage)
        report += f"| {s.step_number} | {stage_str} | {tool_desc} | {status_desc} | {s.tokens_used} |\n"

    report += "\n---\n*Report automatically generated by AI Coding Harness Evaluation System.*\n"
    return report


def generate_json_report(
    state: TaskState,
    metrics: TaskMetrics,
    git_diff: str = "",
) -> Dict[str, Any]:
    """Serializes complete task results into a JSON evaluation payload."""
    status_str = state.status.value if hasattr(state.status, "value") else str(state.status)
    return {
        "task_id": state.task_id,
        "repo_path": state.repo_path,
        "issue_description": state.issue_description,
        "status": status_str,
        "verification_status": state.verification_status or "unverified",
        "failure_category": metrics.failure_category,
        "model": state.model,
        "final_summary": state.final_summary,
        "final_result": state.final_result,
        "error_message": state.error_message,
        "files_modified": state.files_modified,
        "metrics": metrics.model_dump(),
        "git_diff": git_diff,
        "created_at": state.created_at,
        "completed_at": state.completed_at,
        "start_time": state.start_time,
        "completion_time": state.completion_time,
        "steps_count": len(state.steps),
    }


def save_task_reports(
    state: TaskState,
    git_diff: str = "",
    reports_dir: str = ".harness_reports",
) -> Dict[str, str]:
    """Persists task JSON report, Markdown report, and metrics to disk."""
    os.makedirs(reports_dir, exist_ok=True)
    metrics = TaskMetrics.from_task_state(state)
    
    md_content = generate_markdown_report(state, git_diff=git_diff)
    json_data = generate_json_report(state, metrics=metrics, git_diff=git_diff)

    md_path = os.path.join(reports_dir, f"{state.task_id}_report.md")
    json_path = os.path.join(reports_dir, f"{state.task_id}_report.json")

    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md_content)

    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(json_data, f, indent=2)

    return {"markdown_report_path": md_path, "json_report_path": json_path}
